name: rental_app
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.7.2

dependencies:
  flutter:
    sdk: flutter
  firebase_core: ^3.13.0
  firebase_storage_web: ^3.5.0
  cloud_firestore: ^5.6.7
  firebase_auth: ^5.5.3
  firebase_storage: ^12.4.5
  carousel_slider: ^5.0.0
  dots_indicator: ^4.0.1
  image_picker: ^1.1.2
  intl: ^0.19.0
  uuid: ^4.0.0
  flutter_svg: ^2.0.7
  flutter_bloc: ^8.1.3
  equatable: ^2.0.5
  cupertino_icons: ^1.0.8
  js: ^0.6.7
  cloudinary_url_gen: ^1.0.0
  cloudinary_api: ^1.0.0
  http: ^1.1.0
 

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/images/


  fonts:
    - family: BeVietnamPro
      fonts:
        - asset: assets/fonts/BeVietnamPro-Regular.ttf
        - asset: assets/fonts/BeVietnamPro-Bold.ttf
    - family: Conthrax
      fonts:
        - asset: assets/fonts/Conthrax-Regular.ttf

