// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return FirebaseOptions(
        apiKey: 'AIzaSyAcwfj2atmakpjuA4tGPyMjITngYVKsqTY',
        appId: '1:318038145457:android:876cc7e7a11e9808802590',
        messagingSenderId: '318038145457',
        projectId: 'rental-app-flutterfirebase',
        storageBucket: 'rental-app-flutterfirebase.firebasestorage.app',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAcwfj2atmakpjuA4tGPyMjITngYVKsqTY',
    appId: '1:318038145457:android:876cc7e7a11e9808802590',
    messagingSenderId: '318038145457',
    projectId: 'rental-app-flutterfirebase',
    storageBucket: 'rental-app-flutterfirebase.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAiBHE0Wsj9Ht_LkeB1yvY7OMcEItzY6EA',
    appId: '1:318038145457:ios:72871aa3b764d78a802590',
    messagingSenderId: '318038145457',
    projectId: 'rental-app-flutterfirebase',
    storageBucket: 'rental-app-flutterfirebase.firebasestorage.app',
    iosBundleId: 'com.example.rentalApp',
  );

}